language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq iverilog-daily
  - pip install coverage
  - pip install xunitparser
  
#  - export COVERAGE=0
  - export PYTHONPATH=$PYTHONPATH:$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") 
  
#  Build iverilog from source
#  - sudo apt-get install gperf
#  - wget -O iverilog-master.zip  https://github.com/steveicarus/iverilog/archive/master.zip
#  - unzip iverilog-master.zip
#  - cd iverilog-master && autoconf && ./configure && make && sudo make install && cd ..
script:
  - make test
