language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq iverilog-daily
  - pip install coverage
  - pip install xunitparser
  
#  - export COVERAGE=0
  - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages 
  
#  Build iverilog from source
#  - sudo apt-get install gperf
#  - wget -O iverilog-master.zip  https://github.com/steveicarus/iverilog/archive/master.zip
#  - unzip iverilog-master.zip
#  - cd iverilog-master && autoconf && ./configure && make && sudo make install && cd ..
script:
  - make test
